apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: 'arn:aws:secretsmanager:ap-northeast-2:816040392320:secret:rds!db-bc1eb1f6-33e4-4171-913e-14fba30a328a-oNDZMR'
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: username
          - path: password
            objectAlias: password    
  secretObjects:
    - secretName: board-app-secret
      type: Opaque
      data:
        - objectName: username
          key: DB_USER
        - objectName: password
          key: DB_PASSWORD
