apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/board-app
    newName: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-3.amazonaws.com/board-app
    newTag: staging
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: board-app
  - patch: |-
      - op: replace
        path: /data/APP_ENV
        value: staging
      - op: replace
        path: /data/APP_REGION
        value: osaka
      - op: replace
        path: /data/DB_HOST
        value: mysql
    target:
      kind: ConfigMap
      name: board-app-config
  - patch: |-
      - op: replace
        path: /spec/parameters/objects
        value: |
          - objectName: '<AWS_SECRETS_MANAGER_SECRET_ARN>'
            objectType: secretsmanager
            jmesPath:
              - path: username
                objectAlias: username
              - path: password
                objectAlias: password
    target:
      kind: SecretProviderClass
      name: aws-secrets
